// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wliejeubdpqhhbcfhshc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsaWVqZXViZHBxaGhiY2Zoc2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDU0MDUsImV4cCI6MjA1NzI4MTQwNX0.gGE-ut6bkNDe_RsCRTEhLwd16uVAKiCt8BKb75o3VSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);